//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/ClassLibrary")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminClient.ServiceReference.BuySell buySellField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool cancelledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long filledQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool matchedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long orderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminClient.ServiceReference.OrderType orderTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long productIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long quantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime submitTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long traderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long unfilledQuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdminClient.ServiceReference.BuySell buySell {
            get {
                return this.buySellField;
            }
            set {
                if ((this.buySellField.Equals(value) != true)) {
                    this.buySellField = value;
                    this.RaisePropertyChanged("buySell");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool cancelled {
            get {
                return this.cancelledField;
            }
            set {
                if ((this.cancelledField.Equals(value) != true)) {
                    this.cancelledField = value;
                    this.RaisePropertyChanged("cancelled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long filledQuantity {
            get {
                return this.filledQuantityField;
            }
            set {
                if ((this.filledQuantityField.Equals(value) != true)) {
                    this.filledQuantityField = value;
                    this.RaisePropertyChanged("filledQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool matched {
            get {
                return this.matchedField;
            }
            set {
                if ((this.matchedField.Equals(value) != true)) {
                    this.matchedField = value;
                    this.RaisePropertyChanged("matched");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long orderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                if ((this.orderNumberField.Equals(value) != true)) {
                    this.orderNumberField = value;
                    this.RaisePropertyChanged("orderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdminClient.ServiceReference.OrderType orderType {
            get {
                return this.orderTypeField;
            }
            set {
                if ((this.orderTypeField.Equals(value) != true)) {
                    this.orderTypeField = value;
                    this.RaisePropertyChanged("orderType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long productId {
            get {
                return this.productIdField;
            }
            set {
                if ((this.productIdField.Equals(value) != true)) {
                    this.productIdField = value;
                    this.RaisePropertyChanged("productId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime submitTime {
            get {
                return this.submitTimeField;
            }
            set {
                if ((this.submitTimeField.Equals(value) != true)) {
                    this.submitTimeField = value;
                    this.RaisePropertyChanged("submitTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long traderId {
            get {
                return this.traderIdField;
            }
            set {
                if ((this.traderIdField.Equals(value) != true)) {
                    this.traderIdField = value;
                    this.RaisePropertyChanged("traderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long unfilledQuantity {
            get {
                return this.unfilledQuantityField;
            }
            set {
                if ((this.unfilledQuantityField.Equals(value) != true)) {
                    this.unfilledQuantityField = value;
                    this.RaisePropertyChanged("unfilledQuantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuySell", Namespace="http://schemas.datacontract.org/2004/07/ClassLibrary")]
    public enum BuySell : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Buy = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sell = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderType", Namespace="http://schemas.datacontract.org/2004/07/ClassLibrary")]
    public enum OrderType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Market = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Limit = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Trade", Namespace="http://schemas.datacontract.org/2004/07/ClassLibrary")]
    [System.SerializableAttribute()]
    public partial class Trade : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminClient.ServiceReference.BuySell buySellField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal executionPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime executionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal feeAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long oppositeOrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long originalOrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long productIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long quantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal submissionPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long tradeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long traderIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdminClient.ServiceReference.BuySell buySell {
            get {
                return this.buySellField;
            }
            set {
                if ((this.buySellField.Equals(value) != true)) {
                    this.buySellField = value;
                    this.RaisePropertyChanged("buySell");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal executionPrice {
            get {
                return this.executionPriceField;
            }
            set {
                if ((this.executionPriceField.Equals(value) != true)) {
                    this.executionPriceField = value;
                    this.RaisePropertyChanged("executionPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime executionTime {
            get {
                return this.executionTimeField;
            }
            set {
                if ((this.executionTimeField.Equals(value) != true)) {
                    this.executionTimeField = value;
                    this.RaisePropertyChanged("executionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal feeAmount {
            get {
                return this.feeAmountField;
            }
            set {
                if ((this.feeAmountField.Equals(value) != true)) {
                    this.feeAmountField = value;
                    this.RaisePropertyChanged("feeAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long oppositeOrderId {
            get {
                return this.oppositeOrderIdField;
            }
            set {
                if ((this.oppositeOrderIdField.Equals(value) != true)) {
                    this.oppositeOrderIdField = value;
                    this.RaisePropertyChanged("oppositeOrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long originalOrderId {
            get {
                return this.originalOrderIdField;
            }
            set {
                if ((this.originalOrderIdField.Equals(value) != true)) {
                    this.originalOrderIdField = value;
                    this.RaisePropertyChanged("originalOrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long productId {
            get {
                return this.productIdField;
            }
            set {
                if ((this.productIdField.Equals(value) != true)) {
                    this.productIdField = value;
                    this.RaisePropertyChanged("productId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal submissionPrice {
            get {
                return this.submissionPriceField;
            }
            set {
                if ((this.submissionPriceField.Equals(value) != true)) {
                    this.submissionPriceField = value;
                    this.RaisePropertyChanged("submissionPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long tradeId {
            get {
                return this.tradeIdField;
            }
            set {
                if ((this.tradeIdField.Equals(value) != true)) {
                    this.tradeIdField = value;
                    this.RaisePropertyChanged("tradeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long traderId {
            get {
                return this.traderIdField;
            }
            set {
                if ((this.traderIdField.Equals(value) != true)) {
                    this.traderIdField = value;
                    this.RaisePropertyChanged("traderId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IAdminService")]
    public interface IAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetOrders", ReplyAction="http://tempuri.org/IAdminService/GetOrdersResponse")]
        AdminClient.ServiceReference.Order[] GetOrders(long productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetOrders", ReplyAction="http://tempuri.org/IAdminService/GetOrdersResponse")]
        System.Threading.Tasks.Task<AdminClient.ServiceReference.Order[]> GetOrdersAsync(long productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetTrades", ReplyAction="http://tempuri.org/IAdminService/GetTradesResponse")]
        AdminClient.ServiceReference.Trade[] GetTrades(long productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetTrades", ReplyAction="http://tempuri.org/IAdminService/GetTradesResponse")]
        System.Threading.Tasks.Task<AdminClient.ServiceReference.Trade[]> GetTradesAsync(long productId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminServiceChannel : AdminClient.ServiceReference.IAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceClient : System.ServiceModel.ClientBase<AdminClient.ServiceReference.IAdminService>, AdminClient.ServiceReference.IAdminService {
        
        public AdminServiceClient() {
        }
        
        public AdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AdminClient.ServiceReference.Order[] GetOrders(long productId) {
            return base.Channel.GetOrders(productId);
        }
        
        public System.Threading.Tasks.Task<AdminClient.ServiceReference.Order[]> GetOrdersAsync(long productId) {
            return base.Channel.GetOrdersAsync(productId);
        }
        
        public AdminClient.ServiceReference.Trade[] GetTrades(long productId) {
            return base.Channel.GetTrades(productId);
        }
        
        public System.Threading.Tasks.Task<AdminClient.ServiceReference.Trade[]> GetTradesAsync(long productId) {
            return base.Channel.GetTradesAsync(productId);
        }
    }
}
