//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.AdminServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminServiceReference.IAdminService")]
    public interface IAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetOrders", ReplyAction="http://tempuri.org/IAdminService/GetOrdersResponse")]
        ClassLibrary.Order[] GetOrders(long productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetOrders", ReplyAction="http://tempuri.org/IAdminService/GetOrdersResponse")]
        System.Threading.Tasks.Task<ClassLibrary.Order[]> GetOrdersAsync(long productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetTrades", ReplyAction="http://tempuri.org/IAdminService/GetTradesResponse")]
        ClassLibrary.Trade[] GetTrades(long productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetTrades", ReplyAction="http://tempuri.org/IAdminService/GetTradesResponse")]
        System.Threading.Tasks.Task<ClassLibrary.Trade[]> GetTradesAsync(long productId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminServiceChannel : AdminClient.AdminServiceReference.IAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceClient : System.ServiceModel.ClientBase<AdminClient.AdminServiceReference.IAdminService>, AdminClient.AdminServiceReference.IAdminService {
        
        public AdminServiceClient() {
        }
        
        public AdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClassLibrary.Order[] GetOrders(long productId) {
            return base.Channel.GetOrders(productId);
        }
        
        public System.Threading.Tasks.Task<ClassLibrary.Order[]> GetOrdersAsync(long productId) {
            return base.Channel.GetOrdersAsync(productId);
        }
        
        public ClassLibrary.Trade[] GetTrades(long productId) {
            return base.Channel.GetTrades(productId);
        }
        
        public System.Threading.Tasks.Task<ClassLibrary.Trade[]> GetTradesAsync(long productId) {
            return base.Channel.GetTradesAsync(productId);
        }
    }
}
